name: "CI"

on:
    pull_request:
    push:
        branches:
            - 'main'
    schedule:
        -   cron: '0 0 * * *'

env:
    PHPUNIT_FLAGS: "-v"
    SYMFONY_PHPUNIT_DIR: "$HOME/symfony-bridge/.phpunit"

jobs:
    test:
        name: "PHP ${{ matrix.php-version }} + @${{ matrix.symfony-version }} ${{ matrix.dependency-versions }} deps"

        runs-on: ubuntu-18.04

        env:
            SYMFONY_VERSION: ${{ matrix.symfony-version }}
            MAKER_ALLOW_DEV_DEPS_IN_APP: ${{ matrix.allow-dev-deps-in-apps }}

        strategy:
            fail-fast: false
            matrix:
                php-version:
                    - '8.1'
                symfony-version:
                    - '5.4.*'
                    - '5.4.x-dev'
                    - '6.0.x-dev'
                    - '6.1.x-dev'
                    - '6.2.x-dev'
                dependency-versions: [ 'highest' ]
                allow-dev-deps-in-apps: [ '0' ]
                include:
                    # testing lowest PHP version with LTS
                    -   php-version: '8.0.0'
                        symfony-version: '5.4.*'
                        dependency-versions: 'lowest'
                    # testing lowest php version with highest 5.x stable
                    -   php-version: '8.0.0'
                        symfony-version: '5.4.*'
                        dependency-versions: 'highest'

        steps:
            -   name: "Checkout code"
                uses: actions/checkout@v2.3.3

            -   name: "Install PHP with extensions"
                uses: shivammathur/setup-php@v2
                with:
                    coverage: "none"
                    php-version: ${{ matrix.php-version }}
                    tools: composer:v2

            -   name: "Add PHPUnit matcher"
                run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            -   name: "Composer install"
                uses: "ramsey/composer-install@v1"
                with:
                    dependency-versions: "${{ matrix.dependency-versions }}"

            -   name: "Install PHPUnit"
                run: vendor/bin/simple-phpunit install

            -   name: "PHPUnit version"
                run: vendor/bin/simple-phpunit --version

            -   name: "Run tests"
                run: vendor/bin/simple-phpunit ${{ env.PHPUNIT_FLAGS }}
